import { Box, Flex, VStack, Text, Select, HStack, Button, Input, IconButton, useClipboard } from '@chakra-ui/react';
import { CopyIcon, CheckIcon } from '@chakra-ui/icons';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import QR from 'qrcode.react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const address = 'GvHeR432g7MjN9uKyX3Dzg66TqwrEWgANLnnFZXMeyyj';

  const { hasCopied, onCopy } = useClipboard(address);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex flexDir={'column'}>
        {/* <Flex flexDir={'row'} justifyContent={'space-between'}>
          <Text>TempWallet</Text>
          <Text>Wallet</Text>
        </Flex> */}
        <VStack mt={16} alignContent={'center'} justifyContent="center">
          <Select defaultValue={'mainnet'} width="160px" height="36px" textAlign={'center'}>
            <option value="mainnet">Mainnet</option>
            <option value="devnet">Devnet</option>
          </Select>
          <Text fontSize={'5xl'} fontWeight={'600'}>
            $145.40
          </Text>
          <QR
            level={'H'}
            includeMargin={false}
            //ethereum:0x34aA3F359A9D614239015126635CE7732c18fDF3
            value={address} //"https://punkwallet.io/"+
            size={380}
            imageSettings={{
              width: 90,
              height: 90,
              excavate: true,
              src: '/logo.svg',
            }}
          />
          <Text width="380px" fontSize="20px" textAlign="center">
            {address}
            <IconButton onClick={onCopy} aria-label="Search database" icon={hasCopied ? <CheckIcon /> : <CopyIcon />} variant="unstyled" size="xs" />
          </Text>

          <VStack>
            <Box width="380px" padding="1rem 2rem" borderRadius="lg">
              <Flex dir="row" justifyContent="space-between">
                <Text fontSize="28px" fontWeight="500">
                  0.5 SOL
                </Text>
                <Text fontSize="28px" fontWeight="500">
                  $50
                </Text>
              </Flex>
              <Input mt={2} placeholder="To Address" />
              <Flex mt={2} dir="row" justifyContent="space-between">
                <Input placeholder="Amount" mr={4} />
                <Button colorScheme="teal" width="150px" variant="outline">
                  Transfer
                </Button>
              </Flex>
            </Box>
            <Box width="380px" padding="1rem 2rem" borderRadius="lg">
              <Flex dir="row" justifyContent="space-between">
                <Text fontSize="28px" fontWeight="500">
                  95 USDC
                </Text>
                <Text fontSize="28px" fontWeight="500">
                  $95
                </Text>
              </Flex>
              <Input mt={2} placeholder="To Address" />
              <Flex mt={2} dir="row" justifyContent="space-between">
                <Input placeholder="Amount" mr={4} />
                <Button colorScheme="teal" width="150px" variant="outline">
                  Transfer
                </Button>
              </Flex>
            </Box>
          </VStack>
        </VStack>
      </Flex>
    </div>
  );
};
// min-height: 100vh;
// padding: 4rem 0;
// flex: 1;
// display: flex;
// flex-direction: column;
// justify-content: center;
// align-items: center;
export default Home;
